---
- hosts: MSR-test-Instance-2
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    temp_folder: /tmp
  tasks:
    # Install Git    
    - include: tasks/git.yml  
    # Install Node.js    
    - include: tasks/node.yml
    # Install NVM
    #- include: tasks/nvm.yml
    # Install Docker
    - include: tasks/docker.yml
    # Pull Couchdb Image inside Docker
    - include: tasks/couchdb.yml